# Generated by Django 3.1.3 on 2023-05-24 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('image', models.URLField()),
                ('ataque', models.SmallIntegerField(max_length=5)),
                ('defensa', models.SmallIntegerField(max_length=5)),
                ('tipo', models.CharField(max_length=15)),
                ('counter', models.CharField(max_length=15)),
                ('strong', models.CharField(max_length=15)),
            ],
        ),
    ]
