# Generated by Django 3.1.3 on 2023-05-24 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gato',
            name='ataque',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gato',
            name='defensa',
            field=models.SmallIntegerField(),
        ),
    ]
